# fly.toml â€” simplified for Telegram Bot
app = "tpa-affiliate-bot"
primary_region = "sin"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main_bot.py"

[deploy]
  strategy = "immediate"
  max_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
